# Generated by Django 3.2.4 on 2021-06-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('birthday', models.DateField()),
                ('date_registration', models.DateField(auto_now_add=True)),
                ('country', models.CharField(max_length=50)),
                ('avatar_path', models.ImageField(upload_to='blog-site/blogsite/media')),
                ('id_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id_tag', models.IntegerField(primary_key=True, serialize=False)),
                ('id_post', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_tag', 'id_post')},
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_role', 'id_user')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='blog-site/blogsite/media')),
                ('description', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id_comment', models.IntegerField(primary_key=True, serialize=False)),
                ('id_post', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_comment', 'id_post')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('id_post', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_category', 'id_post')},
            },
        ),
    ]
