# Generated by Django 3.2.4 on 2021-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='blog-site/blogsite/media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_path',
            field=models.ImageField(null=True, upload_to='blog-site/blogsite/media'),
        ),
    ]
